name: Test

on:
  push:
    branches:
      - main
    paths:
      - "*.go"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.16

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Generate self signed cert
        run: openssl req -x509 -newkey rsa:4096 -sha256 -days 356 -nodes -keyout key.pem -out cert.pem -subj "/CN=localhost"

      - name: Build
        run: go build -v ./...

      - name: Get gopherbadger
        run: go get github.com/jpoles1/gopherbadger

      - name: Run test
        run: gopherbadger -style=for-the-badge -covercmd "go test -v -race -covermode atomic -coverprofile=coverage.out ./... && go tool cover -func=coverage.out"

      - name: Commit coverage badge
        uses: EndBug/add-and-commit@v7
        with:
          message: "ci: update coverage"
          add: "coverage_badge.png"
          author_name: "github-actions[bot]"
          author_email: "github-actions[bot]@users.noreply.github.com"
